# -*- coding: utf-8 -*-
"""ImageLatentWalk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDQahcLScqvkk4XCGabN3elCHnMVRWRK

# Installation
"""

# !pip install git+https://github.com/huggingface/diffusers.git
# !pip install accelerate transformers
# !pip install imageio imageio-ffmpeg

"""# Imports"""

import torch
from torch import nn
from PIL import Image
from diffusers import Flux2KleinPipeline
from tqdm.auto import tqdm

import warnings
warnings.filterwarnings("ignore")

import os
from datetime import datetime
import imageio.v3 as iio

"""# Define constants"""

HEIGHT = 1024
WIDTH = 1024
# NUM_IMAGES = 64
# NUM_IMAGES = 1024
NUM_IMAGES = 256
DTYPE = torch.bfloat16
SEED = 42

MP4_FRAMERATE = 10
INTERP_METHOD = "linear" # Options: "spherical", "linear"

"""# Define prompts"""

# prompt1 = "Eiffel tower, style of starry night, artistic"
prompt1 = "Dark"
# prompt2 = "Eiffel tower, minimalist style"
# prompt2 = "Golden Gate bridge on a sunny afternoon, from a majestic perspective"
prompt2 = "Light"

"""# Define models and helper functions"""

def spherical_interpolation(latent1, latent2, num_samples):
    actual_dtype = latent1.dtype

    latent1 = latent1.to(torch.float32)
    latent2 = latent2.to(torch.float32)

    def interpolate(latent1, latent2, step, dot_threshold=0.9995):
        dot = torch.sum(
            latent1 * latent2 / (torch.linalg.norm(torch.ravel(latent1)) * torch.linalg.norm(torch.ravel(latent2)))
        )
        if torch.abs(dot) > dot_threshold:
            latent2 = (1 - step) * latent1 + step * latent2
        else:
            theta0 = torch.arccos(dot)
            sin_theta0 = torch.sin(theta0)
            theta_t = theta0 * step
            sin_theta_t = torch.sin(theta_t)

            s0 = torch.sin(theta0 - sin_theta_t) / sin_theta0
            s1 = sin_theta_t / sin_theta0

            latent2 = s0 * latent1 + s1 * latent2

        return latent2

    t = torch.linspace(0, 1, num_samples)
    interpolated = torch.stack([interpolate(latent1, latent2, t[i]) for i in range(num_samples)], axis=0)

    return interpolated.to(actual_dtype)

def linear_interpolation(latent1, latent2, num_samples):
    actual_dtype = latent1.dtype

    latent1 = latent1.to(torch.float32)
    latent2 = latent2.to(torch.float32)

    t = torch.linspace(0, 1, num_samples)
    interpolated = torch.stack([(1 - t[i]) * latent1 + t[i] * latent2 for i in range(num_samples)], axis=0)

    return interpolated.to(actual_dtype)

pipe = Flux2KleinPipeline.from_pretrained(
    "black-forest-labs/FLUX.2-klein-4B", torch_dtype=DTYPE
).to("cuda")
# pipe.enable_model_cpu_offload()

pipe.transformer = torch.compile(pipe.transformer, mode='reduce-overhead')
pipe.vae = torch.compile(pipe.vae, mode='reduce-overhead')

# Safely compile text encoders if they exist on the pipeline
if hasattr(pipe, 'text_encoder') and pipe.text_encoder is not None:
    pipe.text_encoder = torch.compile(pipe.text_encoder, mode='reduce-overhead')

print("Warming up the compiled models (this will take a moment for the first run)...")
for i in range(3):
    _ = pipe(
        prompt="A beautiful landscape, warmup prompt",
        height=HEIGHT,
        width=WIDTH,
        num_inference_steps=4
    )
    print(f"Warmup run {i+1}/3 complete.")

print("Compilation and warmup finished!")

"""# Get text encoder embeddings for both prompts"""

prompt1_embedding, _ = pipe.encode_prompt(prompt1)
prompt2_embedding, _ = pipe.encode_prompt(prompt2)

if INTERP_METHOD == "linear":
    interpolated_embeddings = linear_interpolation(
        latent1=prompt1_embedding,
        latent2=prompt2_embedding,
        num_samples=NUM_IMAGES
    )
else:
    interpolated_embeddings = spherical_interpolation(
        latent1=prompt1_embedding,
        latent2=prompt2_embedding,
        num_samples=NUM_IMAGES
    )

"""# Get images from latent walk and stitch into GIF"""

import time

generator = torch.Generator("cuda").manual_seed(42)
height = 2 * (int(HEIGHT) // (8 * 2)) # from https://github.com/huggingface/diffusers/blob/31058485f1eea5a33e60ce9456c83e16bc4fc221/src/diffusers/pipelines/flux2/pipeline_flux2_klein.py#L200
width = 2 * (int(WIDTH) // (8 * 2))

# Create a base latent for a single image, we will repeat it for the batch
base_latents = torch.randn((1, 128, height // 2, width // 2))

images = []
BATCH_SIZE = 16 # Increase this if you have more VRAM (e.g., 4 or 8 on an A100)

start_time = time.time()

for i in tqdm(range(0, NUM_IMAGES, BATCH_SIZE)):
    # Determine the actual batch size for this step (handles the last partial batch)
    curr_batch_size = min(BATCH_SIZE, NUM_IMAGES - i)

    # Slice the embeddings for the current batch and squeeze out the extra dimension
    batch_embeds = interpolated_embeddings[i : i + curr_batch_size].squeeze(1)

    # Repeat the latents to match the current batch size
    batch_latents = base_latents.repeat(curr_batch_size, 1, 1, 1)

    # Generate a batch of images
    batch_output = pipe(
        prompt_embeds=batch_embeds,
        height=HEIGHT,
        width=WIDTH,
        # num_inference_steps=50,
        num_inference_steps=4,
        # generator=generator,
        latents=batch_latents
    )

    # Add the generated images to our list
    images.extend(batch_output.images)

end_time = time.time()
print(f"Total generation time for {NUM_IMAGES} images: {end_time - start_time:.2f} seconds")

imgs = [im.convert("RGBA") for im in images]

output_folder = datetime.now().strftime("%Y%m%d_%H%M%S")
images_dir = os.path.join(output_folder, "images")
gif_dir = os.path.join(output_folder, "gif")
mp4_dir = os.path.join(output_folder, "mp4")

os.makedirs(images_dir, exist_ok=True)
os.makedirs(gif_dir, exist_ok=True)
os.makedirs(mp4_dir, exist_ok=True)

# Save GIF
gif_path = os.path.join(gif_dir, "out.gif")
imgs[0].save(
    gif_path,
    save_all=True,
    append_images=imgs[1:],
    duration=100,   # ms per frame
    loop=0,        # 0 = forever
    disposal=2     # clear between frames (often avoids trails)
)

# Save Images
for i, img in enumerate(imgs):
    img.save(os.path.join(images_dir, f"image_{i:03d}.png"))

# Save MP4
mp4_path = os.path.join(mp4_dir, "out.mp4")
iio.imwrite(mp4_path, imgs, fps=MP4_FRAMERATE)

print(f"All outputs successfully saved in folder: {output_folder}/")

"""## Control Speed of GIF"""

import ipywidgets as widgets
from IPython.display import display, clear_output
import time
import threading

# Assuming 'imgs' is the list of PIL Images generated in the previous cells
if 'imgs' not in locals() or not imgs:
    print("Please generate images first.")
else:
    play_video = True
    current_delay = 0.1

    def update_speed(change):
        global current_delay
        # Slider value is fps, delay is 1/fps
        current_delay = 1.0 / change.new

    speed_slider = widgets.FloatSlider(
        value=10.0,
        min=1.0,
        max=60.0,
        step=1.0,
        description='FPS:',
        continuous_update=True
    )
    speed_slider.observe(update_speed, names='value')

    stop_button = widgets.Button(description="Stop")

    def stop_playback(b):
        global play_video
        play_video = False

    stop_button.on_click(stop_playback)

    display(widgets.HBox([speed_slider, stop_button]))

    output = widgets.Output()
    display(output)

    def play_frames():
        global play_video, current_delay
        while play_video:
            for img in imgs:
                if not play_video:
                    break
                with output:
                    clear_output(wait=True)
                    display(img)
                time.sleep(current_delay)

    # Run playback in a separate thread so UI remains responsive
    thread = threading.Thread(target=play_frames)
    thread.start()

"""## Prompts to use
- The Eiffel Tower in the style of starry night
"""